export const samplePriceItems = [
  {
    id: "1",
    code: "EXC-001",
    description: "Excavation for foundation",
    category: "Earthworks",
    subCategory: "Excavation",
    unit: "m3",
    rate: 50,
  },
  {
    id: "2",
    code: "CON-001",
    description: "Concrete grade 25",
    category: "Concrete",
    subCategory: "Foundations",
    unit: "m3",
    rate: 120,
  },
  {
    id: "3",
    code: "BRK-001",
    description: "Brick walling 230mm",
    category: "Masonry",
    subCategory: "Walls",
    unit: "m2",
    rate: 45,
  },
  {
    id: "4",
    code: "PLS-001",
    description: "Plastering internal walls",
    category: "Finishes",
    subCategory: "Plaster",
    unit: "m2",
    rate: 15,
  },
  {
    id: "5",
    code: "PNT-001",
    description: "Painting walls with emulsion paint",
    category: "Finishes",
    subCategory: "Painting",
    unit: "m2",
    rate: 10,
  },
]
